#pragma checksum "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\BillingView.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "F5253EBFE28190CE7799DF4EA2495F76042D5562"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RRBridal.StoreBilling.App.Services.Ui;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace RRBridal.StoreBilling.App.Views {
    
    
    /// <summary>
    /// BillingView
    /// </summary>
    public partial class BillingView : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 12 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\BillingView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid MasterDetailGrid;
        
        #line default
        #line hidden
        
        
        #line 88 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\BillingView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border PhoneInputBorder;
        
        #line default
        #line hidden
        
        
        #line 117 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\BillingView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox CustomerPhoneBox;
        
        #line default
        #line hidden
        
        
        #line 127 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\BillingView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox CustomerNameBox;
        
        #line default
        #line hidden
        
        
        #line 156 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\BillingView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid LinesGrid;
        
        #line default
        #line hidden
        
        
        #line 189 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\BillingView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTextColumn ColHsn;
        
        #line default
        #line hidden
        
        
        #line 200 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\BillingView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTextColumn ColDisc;
        
        #line default
        #line hidden
        
        
        #line 202 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\BillingView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTextColumn ColCashDisc;
        
        #line default
        #line hidden
        
        
        #line 204 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\BillingView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTextColumn ColScheme;
        
        #line default
        #line hidden
        
        
        #line 206 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\BillingView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTextColumn ColOrigTax;
        
        #line default
        #line hidden
        
        
        #line 208 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\BillingView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTextColumn ColRevisedAmt;
        
        #line default
        #line hidden
        
        
        #line 210 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\BillingView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTextColumn ColRevisedGst;
        
        #line default
        #line hidden
        
        
        #line 212 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\BillingView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTextColumn ColMrp;
        
        #line default
        #line hidden
        
        
        #line 215 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\BillingView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTextColumn ColTaxPct;
        
        #line default
        #line hidden
        
        
        #line 218 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\BillingView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTextColumn ColCgst;
        
        #line default
        #line hidden
        
        
        #line 220 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\BillingView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTextColumn ColSgst;
        
        #line default
        #line hidden
        
        
        #line 222 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\BillingView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTextColumn ColIgst;
        
        #line default
        #line hidden
        
        
        #line 224 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\BillingView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTextColumn ColTaxAmt;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "9.0.9.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/RRBridal.StoreBilling.App;component/views/billingview.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\BillingView.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "9.0.9.0")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal System.Delegate _CreateDelegate(System.Type delegateType, string handler) {
            return System.Delegate.CreateDelegate(delegateType, this, handler);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "9.0.9.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.MasterDetailGrid = ((System.Windows.Controls.Grid)(target));
            return;
            case 2:
            this.PhoneInputBorder = ((System.Windows.Controls.Border)(target));
            return;
            case 3:
            this.CustomerPhoneBox = ((System.Windows.Controls.TextBox)(target));
            
            #line 122 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\BillingView.xaml"
            this.CustomerPhoneBox.KeyDown += new System.Windows.Input.KeyEventHandler(this.CustomerPhoneBox_OnKeyDown);
            
            #line default
            #line hidden
            
            #line 123 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\BillingView.xaml"
            this.CustomerPhoneBox.LostFocus += new System.Windows.RoutedEventHandler(this.CustomerPhoneBox_OnLostFocus);
            
            #line default
            #line hidden
            return;
            case 4:
            this.CustomerNameBox = ((System.Windows.Controls.TextBox)(target));
            
            #line 132 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\BillingView.xaml"
            this.CustomerNameBox.KeyDown += new System.Windows.Input.KeyEventHandler(this.CustomerNameBox_OnKeyDown);
            
            #line default
            #line hidden
            return;
            case 5:
            this.LinesGrid = ((System.Windows.Controls.DataGrid)(target));
            
            #line 169 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\BillingView.xaml"
            this.LinesGrid.PreparingCellForEdit += new System.EventHandler<System.Windows.Controls.DataGridPreparingCellForEditEventArgs>(this.LinesGrid_OnPreparingCellForEdit);
            
            #line default
            #line hidden
            
            #line 170 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\BillingView.xaml"
            this.LinesGrid.PreviewKeyDown += new System.Windows.Input.KeyEventHandler(this.LinesGrid_OnPreviewKeyDown);
            
            #line default
            #line hidden
            
            #line 171 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\BillingView.xaml"
            this.LinesGrid.CurrentCellChanged += new System.EventHandler<System.EventArgs>(this.LinesGrid_OnCurrentCellChanged);
            
            #line default
            #line hidden
            return;
            case 6:
            this.ColHsn = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            case 7:
            this.ColDisc = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            case 8:
            this.ColCashDisc = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            case 9:
            this.ColScheme = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            case 10:
            this.ColOrigTax = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            case 11:
            this.ColRevisedAmt = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            case 12:
            this.ColRevisedGst = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            case 13:
            this.ColMrp = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            case 14:
            this.ColTaxPct = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            case 15:
            this.ColCgst = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            case 16:
            this.ColSgst = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            case 17:
            this.ColIgst = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            case 18:
            this.ColTaxAmt = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            case 19:
            
            #line 474 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\BillingView.xaml"
            ((System.Windows.Controls.TextBox)(target)).GotFocus += new System.Windows.RoutedEventHandler(this.EditableAmountBox_OnGotFocus);
            
            #line default
            #line hidden
            return;
            case 20:
            
            #line 486 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\BillingView.xaml"
            ((System.Windows.Controls.TextBox)(target)).GotFocus += new System.Windows.RoutedEventHandler(this.EditableAmountBox_OnGotFocus);
            
            #line default
            #line hidden
            return;
            case 21:
            
            #line 498 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\BillingView.xaml"
            ((System.Windows.Controls.TextBox)(target)).GotFocus += new System.Windows.RoutedEventHandler(this.EditableAmountBox_OnGotFocus);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

