#pragma checksum "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\WhatsAppBroadcastDialog.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "ACFDF6E9B4F9546189F2FADFCFCC151D353F4594"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace RRBridal.StoreBilling.App.Views {
    
    
    /// <summary>
    /// WhatsAppBroadcastDialog
    /// </summary>
    public partial class WhatsAppBroadcastDialog : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 19 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\WhatsAppBroadcastDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock SummaryText;
        
        #line default
        #line hidden
        
        
        #line 23 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\WhatsAppBroadcastDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton ModeTemplate;
        
        #line default
        #line hidden
        
        
        #line 25 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\WhatsAppBroadcastDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton ModeSession;
        
        #line default
        #line hidden
        
        
        #line 28 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\WhatsAppBroadcastDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ModeHintText;
        
        #line default
        #line hidden
        
        
        #line 31 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\WhatsAppBroadcastDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel TemplateFieldsPanel;
        
        #line default
        #line hidden
        
        
        #line 33 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\WhatsAppBroadcastDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox OfferTextBox;
        
        #line default
        #line hidden
        
        
        #line 37 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\WhatsAppBroadcastDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox OfferScopeBox;
        
        #line default
        #line hidden
        
        
        #line 41 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\WhatsAppBroadcastDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox OfferDateBox;
        
        #line default
        #line hidden
        
        
        #line 43 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\WhatsAppBroadcastDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock UrlLabel;
        
        #line default
        #line hidden
        
        
        #line 44 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\WhatsAppBroadcastDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox UrlSuffixBox;
        
        #line default
        #line hidden
        
        
        #line 48 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\WhatsAppBroadcastDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel SessionFieldsPanel;
        
        #line default
        #line hidden
        
        
        #line 50 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\WhatsAppBroadcastDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox SessionTextBox;
        
        #line default
        #line hidden
        
        
        #line 55 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\WhatsAppBroadcastDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel MediaPanel;
        
        #line default
        #line hidden
        
        
        #line 60 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\WhatsAppBroadcastDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox MediaPathBox;
        
        #line default
        #line hidden
        
        
        #line 64 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\WhatsAppBroadcastDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock StatusText;
        
        #line default
        #line hidden
        
        
        #line 69 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\WhatsAppBroadcastDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button SendButton;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "9.0.9.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/RRBridal.StoreBilling.App;component/views/whatsappbroadcastdialog.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\WhatsAppBroadcastDialog.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "9.0.9.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.SummaryText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 2:
            this.ModeTemplate = ((System.Windows.Controls.RadioButton)(target));
            
            #line 24 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\WhatsAppBroadcastDialog.xaml"
            this.ModeTemplate.Checked += new System.Windows.RoutedEventHandler(this.Mode_Changed);
            
            #line default
            #line hidden
            return;
            case 3:
            this.ModeSession = ((System.Windows.Controls.RadioButton)(target));
            
            #line 26 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\WhatsAppBroadcastDialog.xaml"
            this.ModeSession.Checked += new System.Windows.RoutedEventHandler(this.Mode_Changed);
            
            #line default
            #line hidden
            return;
            case 4:
            this.ModeHintText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 5:
            this.TemplateFieldsPanel = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 6:
            this.OfferTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 7:
            this.OfferScopeBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 8:
            this.OfferDateBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 9:
            this.UrlLabel = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 10:
            this.UrlSuffixBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 11:
            this.SessionFieldsPanel = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 12:
            this.SessionTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 13:
            this.MediaPanel = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 14:
            
            #line 59 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\WhatsAppBroadcastDialog.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.BrowseMedia_Click);
            
            #line default
            #line hidden
            return;
            case 15:
            this.MediaPathBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 16:
            this.StatusText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 17:
            
            #line 68 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\WhatsAppBroadcastDialog.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Cancel_Click);
            
            #line default
            #line hidden
            return;
            case 18:
            this.SendButton = ((System.Windows.Controls.Button)(target));
            
            #line 70 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\WhatsAppBroadcastDialog.xaml"
            this.SendButton.Click += new System.Windows.RoutedEventHandler(this.Send_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

