#pragma checksum "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\BarcodeLabelPrintPreviewWindow.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "E1560B8EB63B7306F76D2237AC869BB028D4B429"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RRBridal.StoreBilling.App.Views.Controls;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace RRBridal.StoreBilling.App.Views {
    
    
    /// <summary>
    /// BarcodeLabelPrintPreviewWindow
    /// </summary>
    public partial class BarcodeLabelPrintPreviewWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 27 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\BarcodeLabelPrintPreviewWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border ResultBanner;
        
        #line default
        #line hidden
        
        
        #line 28 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\BarcodeLabelPrintPreviewWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ResultText;
        
        #line default
        #line hidden
        
        
        #line 33 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\BarcodeLabelPrintPreviewWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.WrapPanel LabelsPanel;
        
        #line default
        #line hidden
        
        
        #line 40 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\BarcodeLabelPrintPreviewWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox PrinterCombo;
        
        #line default
        #line hidden
        
        
        #line 42 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\BarcodeLabelPrintPreviewWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock PrinterWarningText;
        
        #line default
        #line hidden
        
        
        #line 47 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\BarcodeLabelPrintPreviewWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock SummaryText;
        
        #line default
        #line hidden
        
        
        #line 52 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\BarcodeLabelPrintPreviewWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button PrintButton;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "9.0.9.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/RRBridal.StoreBilling.App;component/views/barcodelabelprintpreviewwindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\BarcodeLabelPrintPreviewWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "9.0.9.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.ResultBanner = ((System.Windows.Controls.Border)(target));
            return;
            case 2:
            this.ResultText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 3:
            this.LabelsPanel = ((System.Windows.Controls.WrapPanel)(target));
            return;
            case 4:
            this.PrinterCombo = ((System.Windows.Controls.ComboBox)(target));
            
            #line 41 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\BarcodeLabelPrintPreviewWindow.xaml"
            this.PrinterCombo.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.PrinterCombo_OnSelectionChanged);
            
            #line default
            #line hidden
            return;
            case 5:
            this.PrinterWarningText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 6:
            this.SummaryText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 7:
            
            #line 50 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\BarcodeLabelPrintPreviewWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.SaveEpl_OnClick);
            
            #line default
            #line hidden
            return;
            case 8:
            this.PrintButton = ((System.Windows.Controls.Button)(target));
            
            #line 53 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\BarcodeLabelPrintPreviewWindow.xaml"
            this.PrintButton.Click += new System.Windows.RoutedEventHandler(this.Print_OnClick);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

