#pragma checksum "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\BillLookupView.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "9C61C629E28C442A8979B0854C8213DAEC7926C4"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RRBridal.StoreBilling.App.Services.Ui;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace RRBridal.StoreBilling.App.Views {
    
    
    /// <summary>
    /// BillLookupView
    /// </summary>
    public partial class BillLookupView : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 25 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\BillLookupView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox BillNoBox;
        
        #line default
        #line hidden
        
        
        #line 88 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\BillLookupView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid MasterDetailGrid;
        
        #line default
        #line hidden
        
        
        #line 181 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\BillLookupView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid LinesGrid;
        
        #line default
        #line hidden
        
        
        #line 199 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\BillLookupView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTextColumn ColHsn;
        
        #line default
        #line hidden
        
        
        #line 209 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\BillLookupView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTextColumn ColDisc;
        
        #line default
        #line hidden
        
        
        #line 211 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\BillLookupView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTextColumn ColCashDisc;
        
        #line default
        #line hidden
        
        
        #line 213 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\BillLookupView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTextColumn ColScheme;
        
        #line default
        #line hidden
        
        
        #line 215 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\BillLookupView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTextColumn ColOrigTax;
        
        #line default
        #line hidden
        
        
        #line 217 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\BillLookupView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTextColumn ColRevisedAmt;
        
        #line default
        #line hidden
        
        
        #line 219 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\BillLookupView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTextColumn ColRevisedGst;
        
        #line default
        #line hidden
        
        
        #line 221 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\BillLookupView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTextColumn ColMrp;
        
        #line default
        #line hidden
        
        
        #line 223 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\BillLookupView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTextColumn ColTaxPct;
        
        #line default
        #line hidden
        
        
        #line 225 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\BillLookupView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTextColumn ColCgst;
        
        #line default
        #line hidden
        
        
        #line 227 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\BillLookupView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTextColumn ColSgst;
        
        #line default
        #line hidden
        
        
        #line 229 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\BillLookupView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTextColumn ColIgst;
        
        #line default
        #line hidden
        
        
        #line 231 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\BillLookupView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTextColumn ColTaxAmt;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "9.0.9.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/RRBridal.StoreBilling.App;component/views/billlookupview.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\BillLookupView.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "9.0.9.0")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal System.Delegate _CreateDelegate(System.Type delegateType, string handler) {
            return System.Delegate.CreateDelegate(delegateType, this, handler);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "9.0.9.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.BillNoBox = ((System.Windows.Controls.TextBox)(target));
            
            #line 30 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\BillLookupView.xaml"
            this.BillNoBox.KeyDown += new System.Windows.Input.KeyEventHandler(this.BillNoBox_KeyDown);
            
            #line default
            #line hidden
            return;
            case 2:
            
            #line 37 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\BillLookupView.xaml"
            ((System.Windows.Controls.TextBox)(target)).KeyDown += new System.Windows.Input.KeyEventHandler(this.BillNoBox_KeyDown);
            
            #line default
            #line hidden
            return;
            case 3:
            
            #line 44 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\BillLookupView.xaml"
            ((System.Windows.Controls.TextBox)(target)).KeyDown += new System.Windows.Input.KeyEventHandler(this.BillNoBox_KeyDown);
            
            #line default
            #line hidden
            return;
            case 4:
            
            #line 70 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\BillLookupView.xaml"
            ((System.Windows.Controls.DataGrid)(target)).MouseDoubleClick += new System.Windows.Input.MouseButtonEventHandler(this.SearchResults_MouseDoubleClick);
            
            #line default
            #line hidden
            return;
            case 5:
            this.MasterDetailGrid = ((System.Windows.Controls.Grid)(target));
            return;
            case 6:
            this.LinesGrid = ((System.Windows.Controls.DataGrid)(target));
            return;
            case 7:
            this.ColHsn = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            case 8:
            this.ColDisc = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            case 9:
            this.ColCashDisc = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            case 10:
            this.ColScheme = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            case 11:
            this.ColOrigTax = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            case 12:
            this.ColRevisedAmt = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            case 13:
            this.ColRevisedGst = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            case 14:
            this.ColMrp = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            case 15:
            this.ColTaxPct = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            case 16:
            this.ColCgst = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            case 17:
            this.ColSgst = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            case 18:
            this.ColIgst = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            case 19:
            this.ColTaxAmt = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

