#pragma checksum "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\InventoryAdjustStockDialog.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "7271B97F724DFEFC29AB4C71F808935CD7D21FB5"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace RRBridal.StoreBilling.App.Views {
    
    
    /// <summary>
    /// InventoryAdjustStockDialog
    /// </summary>
    public partial class InventoryAdjustStockDialog : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 30 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\InventoryAdjustStockDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox SkuBox;
        
        #line default
        #line hidden
        
        
        #line 35 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\InventoryAdjustStockDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox ProductBox;
        
        #line default
        #line hidden
        
        
        #line 40 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\InventoryAdjustStockDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox CurrentQtyBox;
        
        #line default
        #line hidden
        
        
        #line 51 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\InventoryAdjustStockDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ModeBox;
        
        #line default
        #line hidden
        
        
        #line 59 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\InventoryAdjustStockDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox QuantityBox;
        
        #line default
        #line hidden
        
        
        #line 65 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\InventoryAdjustStockDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox ReasonBox;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "9.0.9.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/RRBridal.StoreBilling.App;component/views/inventoryadjuststockdialog.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\InventoryAdjustStockDialog.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "9.0.9.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.SkuBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 2:
            this.ProductBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 3:
            this.CurrentQtyBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 4:
            this.ModeBox = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 5:
            this.QuantityBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 6:
            this.ReasonBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 7:
            
            #line 70 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\InventoryAdjustStockDialog.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Cancel_OnClick);
            
            #line default
            #line hidden
            return;
            case 8:
            
            #line 72 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\InventoryAdjustStockDialog.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Apply_OnClick);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

