#pragma checksum "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\RecordCreditPaymentDialog.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "A009ECC49D8D95A9612C1AB5947476AB71D98AD2"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace RRBridal.StoreBilling.App.Views {
    
    
    /// <summary>
    /// RecordCreditPaymentDialog
    /// </summary>
    public partial class RecordCreditPaymentDialog : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 11 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\RecordCreditPaymentDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock BalanceHintText;
        
        #line default
        #line hidden
        
        
        #line 16 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\RecordCreditPaymentDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox AmountBox;
        
        #line default
        #line hidden
        
        
        #line 17 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\RecordCreditPaymentDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock RemainingPreviewText;
        
        #line default
        #line hidden
        
        
        #line 23 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\RecordCreditPaymentDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton CashRadio;
        
        #line default
        #line hidden
        
        
        #line 24 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\RecordCreditPaymentDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton UpiRadio;
        
        #line default
        #line hidden
        
        
        #line 25 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\RecordCreditPaymentDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton CardRadio;
        
        #line default
        #line hidden
        
        
        #line 26 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\RecordCreditPaymentDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton CreditNoteRadio;
        
        #line default
        #line hidden
        
        
        #line 27 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\RecordCreditPaymentDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton SplitRadio;
        
        #line default
        #line hidden
        
        
        #line 31 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\RecordCreditPaymentDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel ReferencePanel;
        
        #line default
        #line hidden
        
        
        #line 32 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\RecordCreditPaymentDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ReferenceLabelText;
        
        #line default
        #line hidden
        
        
        #line 33 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\RecordCreditPaymentDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TransactionNoBox;
        
        #line default
        #line hidden
        
        
        #line 37 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\RecordCreditPaymentDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel CreditNotePanel;
        
        #line default
        #line hidden
        
        
        #line 39 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\RecordCreditPaymentDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox CreditNoteCombo;
        
        #line default
        #line hidden
        
        
        #line 42 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\RecordCreditPaymentDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox CreditNoteRefBox;
        
        #line default
        #line hidden
        
        
        #line 46 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\RecordCreditPaymentDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel SplitPanel;
        
        #line default
        #line hidden
        
        
        #line 49 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\RecordCreditPaymentDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock SplitRemainingText;
        
        #line default
        #line hidden
        
        
        #line 64 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\RecordCreditPaymentDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox SplitCashBox;
        
        #line default
        #line hidden
        
        
        #line 66 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\RecordCreditPaymentDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox SplitCardBox;
        
        #line default
        #line hidden
        
        
        #line 68 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\RecordCreditPaymentDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox SplitUpiBox;
        
        #line default
        #line hidden
        
        
        #line 70 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\RecordCreditPaymentDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox SplitCreditNoteAmountBox;
        
        #line default
        #line hidden
        
        
        #line 71 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\RecordCreditPaymentDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox SplitCreditNoteRefBox;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "9.0.9.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/RRBridal.StoreBilling.App;component/views/recordcreditpaymentdialog.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\RecordCreditPaymentDialog.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "9.0.9.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.BalanceHintText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 2:
            this.AmountBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 3:
            this.RemainingPreviewText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 4:
            this.CashRadio = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 5:
            this.UpiRadio = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 6:
            this.CardRadio = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 7:
            this.CreditNoteRadio = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 8:
            this.SplitRadio = ((System.Windows.Controls.RadioButton)(target));
            return;
            case 9:
            this.ReferencePanel = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 10:
            this.ReferenceLabelText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 11:
            this.TransactionNoBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 12:
            this.CreditNotePanel = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 13:
            this.CreditNoteCombo = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 14:
            this.CreditNoteRefBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 15:
            this.SplitPanel = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 16:
            this.SplitRemainingText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 17:
            this.SplitCashBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 18:
            this.SplitCardBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 19:
            this.SplitUpiBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 20:
            this.SplitCreditNoteAmountBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 21:
            this.SplitCreditNoteRefBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 22:
            
            #line 77 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\RecordCreditPaymentDialog.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Cancel_Click);
            
            #line default
            #line hidden
            return;
            case 23:
            
            #line 78 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\RecordCreditPaymentDialog.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Confirm_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

