#pragma checksum "..\..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\Controls\BarcodeLabelPreviewControl.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "1E8F8BDD4E12713D0BFF121958829CF126AE67A1"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace RRBridal.StoreBilling.App.Views.Controls {
    
    
    /// <summary>
    /// BarcodeLabelPreviewControl
    /// </summary>
    public partial class BarcodeLabelPreviewControl : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 9 "..\..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\Controls\BarcodeLabelPreviewControl.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock SkuHeader;
        
        #line default
        #line hidden
        
        
        #line 21 "..\..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\Controls\BarcodeLabelPreviewControl.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Canvas LabelCanvas;
        
        #line default
        #line hidden
        
        
        #line 26 "..\..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\Controls\BarcodeLabelPreviewControl.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Canvas RightCanvas;
        
        #line default
        #line hidden
        
        
        #line 30 "..\..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\Controls\BarcodeLabelPreviewControl.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock SizeCaption;
        
        #line default
        #line hidden
        
        
        #line 31 "..\..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\Controls\BarcodeLabelPreviewControl.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock CopyCaption;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "9.0.9.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri(("/RRBridal.StoreBilling.App;component/views/controls/barcodelabelpreviewcontrol.xa" +
                    "ml"), System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\Controls\BarcodeLabelPreviewControl.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "9.0.9.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.SkuHeader = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 2:
            this.LabelCanvas = ((System.Windows.Controls.Canvas)(target));
            return;
            case 3:
            this.RightCanvas = ((System.Windows.Controls.Canvas)(target));
            return;
            case 4:
            this.SizeCaption = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 5:
            this.CopyCaption = ((System.Windows.Controls.TextBlock)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

