#pragma checksum "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\LoginWindow.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "E76EAE0CCF0251FE026C5F5CA0CCB378206084E2"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RRBridal.StoreBilling.App.Views.Controls;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace RRBridal.StoreBilling.App.Views {
    
    
    /// <summary>
    /// LoginWindow
    /// </summary>
    public partial class LoginWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 16 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\LoginWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid RootLayout;
        
        #line default
        #line hidden
        
        
        #line 20 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\LoginWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ColumnDefinition BrandColumn;
        
        #line default
        #line hidden
        
        
        #line 24 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\LoginWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border BrandPanel;
        
        #line default
        #line hidden
        
        
        #line 80 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\LoginWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox EmailBox;
        
        #line default
        #line hidden
        
        
        #line 90 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\LoginWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock EmailPlaceholder;
        
        #line default
        #line hidden
        
        
        #line 100 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\LoginWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.PasswordBox PasswordBox;
        
        #line default
        #line hidden
        
        
        #line 109 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\LoginWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock PasswordPlaceholder;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "9.0.9.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/RRBridal.StoreBilling.App;component/views/loginwindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\LoginWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "9.0.9.0")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal System.Delegate _CreateDelegate(System.Type delegateType, string handler) {
            return System.Delegate.CreateDelegate(delegateType, this, handler);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "9.0.9.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 15 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\LoginWindow.xaml"
            ((RRBridal.StoreBilling.App.Views.LoginWindow)(target)).SizeChanged += new System.Windows.SizeChangedEventHandler(this.LoginWindow_OnSizeChanged);
            
            #line default
            #line hidden
            return;
            case 2:
            this.RootLayout = ((System.Windows.Controls.Grid)(target));
            return;
            case 3:
            this.BrandColumn = ((System.Windows.Controls.ColumnDefinition)(target));
            return;
            case 4:
            this.BrandPanel = ((System.Windows.Controls.Border)(target));
            return;
            case 5:
            this.EmailBox = ((System.Windows.Controls.TextBox)(target));
            
            #line 87 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\LoginWindow.xaml"
            this.EmailBox.GotFocus += new System.Windows.RoutedEventHandler(this.EmailBox_OnGotFocus);
            
            #line default
            #line hidden
            
            #line 88 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\LoginWindow.xaml"
            this.EmailBox.LostFocus += new System.Windows.RoutedEventHandler(this.EmailBox_OnLostFocus);
            
            #line default
            #line hidden
            
            #line 89 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\LoginWindow.xaml"
            this.EmailBox.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.EmailBox_OnTextChanged);
            
            #line default
            #line hidden
            return;
            case 6:
            this.EmailPlaceholder = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 7:
            this.PasswordBox = ((System.Windows.Controls.PasswordBox)(target));
            
            #line 106 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\LoginWindow.xaml"
            this.PasswordBox.GotFocus += new System.Windows.RoutedEventHandler(this.PasswordBox_OnGotFocus);
            
            #line default
            #line hidden
            
            #line 107 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\LoginWindow.xaml"
            this.PasswordBox.LostFocus += new System.Windows.RoutedEventHandler(this.PasswordBox_OnLostFocus);
            
            #line default
            #line hidden
            
            #line 108 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\LoginWindow.xaml"
            this.PasswordBox.PasswordChanged += new System.Windows.RoutedEventHandler(this.PasswordBox_OnPasswordChanged);
            
            #line default
            #line hidden
            return;
            case 8:
            this.PasswordPlaceholder = ((System.Windows.Controls.TextBlock)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

