#pragma checksum "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\PhysicalInventoryImportPreviewDialog.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "C6DE69E742DA8A28BD0A3D8D851C84598BBC07BA"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace RRBridal.StoreBilling.App.Views {
    
    
    /// <summary>
    /// PhysicalInventoryImportPreviewDialog
    /// </summary>
    public partial class PhysicalInventoryImportPreviewDialog : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 21 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\PhysicalInventoryImportPreviewDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock SummaryText;
        
        #line default
        #line hidden
        
        
        #line 24 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\PhysicalInventoryImportPreviewDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid PreviewGrid;
        
        #line default
        #line hidden
        
        
        #line 41 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\PhysicalInventoryImportPreviewDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ErrorsText;
        
        #line default
        #line hidden
        
        
        #line 50 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\PhysicalInventoryImportPreviewDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox ReasonBox;
        
        #line default
        #line hidden
        
        
        #line 58 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\PhysicalInventoryImportPreviewDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ApplyButton;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "9.0.9.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri(("/RRBridal.StoreBilling.App;component/views/physicalinventoryimportpreviewdialog.x" +
                    "aml"), System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\PhysicalInventoryImportPreviewDialog.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "9.0.9.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.SummaryText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 2:
            this.PreviewGrid = ((System.Windows.Controls.DataGrid)(target));
            return;
            case 3:
            this.ErrorsText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 4:
            this.ReasonBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 5:
            
            #line 57 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\PhysicalInventoryImportPreviewDialog.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Cancel_OnClick);
            
            #line default
            #line hidden
            return;
            case 6:
            this.ApplyButton = ((System.Windows.Controls.Button)(target));
            
            #line 58 "..\..\..\..\..\src\RRBridal.StoreBilling.App\Views\PhysicalInventoryImportPreviewDialog.xaml"
            this.ApplyButton.Click += new System.Windows.RoutedEventHandler(this.Apply_OnClick);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

